
export const aboutStyles = {
  wrapper: {
    boxSizing: 'border-box',
    margin: 0,
    minWidth: 0,
    display: 'flex',
    position: 'relative',
    flexDirection: ['column-reverse', null, null, 'row'],
    alignItems: 'center',
    justifyContent: 'center',
    mb: ['64px', '80px', '192px'],
    pt: ['64px', '80px', null, '32px'],
    px: ['8px', '16px', '24px'],
  },
  column: {
    m: 0,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    maxWidth: '600px',
    mr: [0, null, null, '96px'],
  },
  heading: {
    margin: 0,
    minWidth: 0,
    maxWidth: '600px',
    mb: ['24px', null, null, '48px'],
  },
  header: {
    m: 0,
    minWidth: 0,
    lineHeight: 1,
    letterSpacing: '.005em',
    fontWeight: 'heading',
    textRransform: 'uppercase',
    color: 'black',
    fontSize: ['38px', null, null, '58px'],
  },
  paragraph: {
    m: 0,
    minWidth: 0,
    fontFamily: '"Open Sans"',
    lineHeight: 1.5,
    fontWeight: 300,
    color: 'text',
    fontSize: 2,
    mb: ['24px', null, null, '48px'],
  },
  ctaButton: {
    m: 0,
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  ctaBlurb: {
    m: 0,
    minWidth: 0,
    letterSpacing: '.005em',
    fontFamily: 'body',
    lineHeight: 1,
    fontWeight: 'heading',
    textTransform: 'uppercase',
    color: 'black',
    fontSize: 3,
    marginRight: '16px',
  },
  circle: {
    margin: 0,
    minWidth: 0,
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    border: ' 1px solid white',
    width: '50px',
    height: '50px',
    overflow: ' hidden',
    bg: 'transparent',
    borderColor: 'blue',
  },
  circleImage: {
    bg: 'primary',
    backgroundSize: '40%',
    width: '35px',
    height: '35px',
  }
};