export const headerStyles = {
  wrapper: {
    boxSizing: 'border-box',
    m: 0,
    mt: '-60px',
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    top: 0,
    height: '100vh',
    minHeight: '400px',
    maxHeight: '800px',
    overflow: 'hidden',
    background: 'hsla(190, 74%, 59%, 1)',
    background: 'linear-gradient(45deg, hsla(190, 74%, 59%, 0.8) 17%, hsla(202, 100%, 50%, 1) 100%)',

  },
  anglBox1: {
    boxSizing: 'border-box',
    margin: 0,
    minWidth: 0,
    position: 'absolute',
    bottom: 0,
    left: 0,
    height: 0,
    width: 0,
    borderRight: '15vw solid transparent',
    borderBottom: '15vh solid #f6f6f6',
    zIndex: 2,
  },
  anglBox2: {
    boxSizing: 'border-box',
    margin: 0,
    minWidth: 0,
    position: 'absolute',
    bottom: 0,
    right: 0,
    height: 0,
    width: 0,
    borderLeft: '85vw solid transparent',
    borderBottom: '15vh solid #f6f6f6',
    zIndex: 2,
  }
}