export const navStyles = {
  wrapper: {
    bg: 'transparent',
    display: ['none', 'none', 'flex'],
    justifyContent: 'center',
    color: 'white',
    fontWeight: 'heading',
    fontSize: [1, null, 2, 3],
    zIndex: 1000,
    ml: 4,
  },
  container: {
    display: 'flex',
    alignItems: 'center',
    list: {
      display: 'flex',
      flexDirection: 'column',
      p: 0,
      m: 0,
      circle: {
        boxSizing: 'border-box',
        margin: 0,
        minWidth: 0,
        display: 'flex',
        position: 'relative',
        borderRadius: '50%',
        WebkitAlignItems: 'center',
        WebkitBoxAlign: 'center',
        msFlexAlign: 'center',
        alignItems: 'center',
        WebkitBoxPack: 'center',
        WebkitJustifyContent: 'center',
        msFlexPack: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        border: '1px solid #f6f6f6',
        width: ['50px', null, '70px', null, '90px'],
        height: ['50px', null, '70px', null, '90px'],
        overflow: 'hidden',
        bg: 'transparent',
        marginTop: '8px',
        marginBottom: '8px',
        '&:hover': {
          bg: 'primary',
          color: 'darkBlue',
        },
        'a': {
          m: 0,
          lineHeight: 1,
          textTransform: 'uppercase',
          letterSpacing: '1px',
          fontSize: [0, null, 0, null, 2],
          position: ' absolute',
        }
      }
    }
  },
  mobileWrapper: {
    display: ['block', 'block', 'none'],
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
  },
  mobileContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: '100vw',
    height: '100vh',
    bg: 'text',
  },
  menuToggle: {
    padding: 0,
    outline: 'none',
    border: 'none',
    cursor: 'pointer',
    position: 'absolute',
    top: '18px',
    left: '90vw',
    transform: 'translate(-6vw, 0)',
    borderRadius: '50%',
    bg: 'transparent',
  },
  menuList: {
    m: 0,
    padding: '25px',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '230px',
  },
  menuItem: {
    m: 0,
    padding: 0,
    mb: '40px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    textAlign: 'center',
    color: 'primary',
    fontSize: '40px'
  }
}